### ISSUE TITLE
Inauro Commissioning

### ISSUE THREAD

**Issue by Shiny380** [NubeIO/commissioning-scripts-rubix-os#4]
Similar to CPS
Read in from spreadsheet. 2 functions: Sensor setup, Server setup

Example sheet: https://docs.google.com/spreadsheets/d/1VGRCfpXn5gA20UzXJ3cBTXeRNDpjEaHU2vwqeqXpZyA/edit#gid=45077193

## Sensor / Gateway
Add each sensor in the `Sensor Schedule` sheet
- ROS Location determined by
- - ROS Group determined by
- ROS Gateway determined by `gatewayRef`
- Network/Plugin type determined by `networkRef`. Only need LoRaWAN and LoRaRAW for now
- Histories determined by `Push Rate`
#### Device Tags
- `sensorMake`: `sensorMake` in spreadsheet
- `sensorModel`: `sensorModel` in spreadsheet
- `sensorRef`: last 8 chars of `sensorID` in spreadsheet (i.e. 6d151406)

## Server
Edit the `inauroazuresync` plugin config based of the `Gateway Shedule` sheet

- `hostname`: `IoT Hub Host` in sheet header box
- For each gateway
    - `hos_...`: host UUID
        - `azuredeviceid`: `iotDeviceID` in sheet
        - etc. etc.

#### Example Config
```
azure:
  hostname: iot-labs-shared-sandpit-ae-01.azure-devices.net
  gatewaydetails:
    hos_9257951d85d04e09:
      azuredeviceid: NUBE-DEVGATEWAY02
      azuredevicekey: HFSPUv1Yv1wqd8Pkt+MPIFI3MbPJVJumclZQTzkVe6c=
      routerimei: '---'
      simiccid: '---'
      latitude: "-34.199977"
      longitude: "150.977487"
      networktype: Wired
    host_xxxxxxxxxx:
      azuredeviceid: ""
      azuredevicekey: ""
      routerimei: ""
      simiccid: ""
      latitude: ""
      longitude: ""
      networktype: ""
job:
  sensor_history_sync_frequency: 5m
  gateway_payload_sync_frequency: 15m
log_level: DEBUG
```
